name: Pro Proxy Checker

on:
  workflow_dispatch:
    inputs:
      proxy_input:
        description: 'Paste Link or Proxy List (IP:Port)'
        required: true
      default_proto:
        description: 'If protocol is missing, use:'
        type: choice
        options:
          - http
          - socks4
          - socks5
        default: 'http'

jobs:
  run-checker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install aiohttp aiohttp_socks

      - name: Run Proxy Test
        env:
          PROXY_INPUT: ${{ github.event.inputs.proxy_input }}
          DEFAULT_PROTO: ${{ github.event.inputs.default_proto }}
        run: python checker.py

      - name: Save Results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add results/*.txt
          git commit -m "Updated proxies: $(date)" || exit 0
          git push
